Algoritmo "teste_saída"
// 
//  
// Descrição   : teste de saída
// Autor(a)    : Américo Godoy
// Data atual  : 02/08/2023
Var
// Seção de Declarações das variáveis



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
// comando - escreva, faz o prog. apresentar o que está escrito entre parenteses.
// comando - escreval, faz com que a linha seja quebrada.
   escreval("Bom dia!")
   escreva("Bom dia!")

Fimalgoritmo