Algoritmo "teste_saida_exemplo"
// 
//  
// Descrição   : saída com o comando de saída
// Autor(a)    : Américo Godoy
// Data atual  : 02/08/2023
Var
// Seção de Declarações das variáveis 
   a : inteiro
   b : real
   c : caractere
   d : logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// comando de saída => escreval(----)

   a <- 32
   b <- 2.34567
   c <- "Maria"
   d <- Verdadeiro

   escreval(a)
   escreval(b)
   escreval(c)
   escreval(d)

Fimalgoritmo