Algoritmo "teste_saida_ex2"

// comando de saída com várias expressões de uma só vez.

Var
// Seção de Declarações das variáveis

   idade : inteiro
   salario : real
   nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   idade <- 32
   salario <- 4560.9
   nome <- "Maria Silva"

   escreva("A funcionária ", nome, " ganha ", salario:8:2, " e tem ", idade, " anos.")

Fimalgoritmo