Algoritmo "7DARDO"


Var

d1,d2,d3 : real

Inicio

escreval("Informe o primeiro aremeço:")
leia (d1)
escreval("Informe o segundo aremeço:")
leia (d2)
escreval("Informe o terceiro aremeço:")
leia (d3)

se (d1 >= d2) e (d1 >= d3) então
escreval ("maior distancia:",d1)
fimalgoritmo
fimse

se (d2 >= d1) e (d2 >= d3) então
escreval ("maior distancia:",d2)
fimalgoritmo
fimse

se (d3 >= d2) e (d3 >= d1) então
escreval ("maior distancia:",d3)
fimalgoritmo
fimse

Fimalgoritmo